const $ = (selector) => document.querySelector(selector);
const state = { active: null, pendingTransactionId: null, requestId: 0 };

function setView(view) { for (const id of ['empty-state', 'loading-state', 'error-state', 'results']) $(`#${id}`).hidden = id !== view; }
function text(value, fallback = '—') { return value === null || value === undefined || value === '' ? fallback : String(value); }
function actionName(value) { return text(value, 'NO ACTION').replaceAll('_', ' '); }
function percent(value) { return value === null || value === undefined ? '—' : `${Math.round(Number(value) * 100)}%`; }
async function api(path, options = {}) { const response = await fetch(path, { headers: { 'content-type': 'application/json', ...(options.headers ?? {}) }, ...options }); const payload = await response.json().catch(() => ({ ok: false, error: `HTTP ${response.status}` })); if (!response.ok || payload.ok === false) throw new Error(payload.error ?? payload.detail ?? `API request failed (${response.status})`); return payload; }
function setApiStatus(ok, label) { $('#api-status').textContent = label; $('#api-pulse').className = `pulse-dot ${ok ? 'ok' : 'bad'}`; }
function setInputStatus(message, kind = '') { const el = $('#input-status'); el.hidden = !message; el.textContent = message ?? ''; el.className = `input-status ${kind}`.trim(); }
function recordFromCaseDetail(detail) { return detail?.record?.data?.record ?? detail?.record ?? null; }
function transactionFromRecord(record) { return record?.trigger?.transaction_id ?? record?.transaction_id ?? null; }
function caseIdFromRecord(record) { return record?.case_id ?? null; }
function showError(error) { setView('error-state'); $('#error-message').textContent = error instanceof Error ? error.message : String(error); $('#investigate-button').disabled = false; setInputStatus('Investigation failed — no active case is displayed.', 'error'); }
function ruleRow(target, rules = []) { target.replaceChildren(); for (const rule of rules) { const el = document.createElement('span'); el.className = 'rule'; el.textContent = rule; target.append(el); } }
function itemCard(title, body, meta = '', className = 'neutral') { const el = document.createElement('div'); el.className = `stack-item ${className}`; const top = document.createElement('div'); top.className = 'stack-top'; const strong = document.createElement('strong'); strong.textContent = title; top.append(strong); const p = document.createElement('p'); p.textContent = body; el.append(top, p); if (meta) { const m = document.createElement('div'); m.className = 'stack-meta'; m.textContent = meta; el.append(m); } return el; }
function clearRenderedCase() {
  state.active = null; state.pendingTransactionId = null; $('#case-title').textContent = 'Awaiting transaction'; $('#case-id-chip').textContent = 'NO CASE'; $('#case-status-chip').textContent = 'OPEN'; $('#mini-case-id').textContent = '—'; $('#case-mini').hidden = true; $('#mini-step').textContent = '0'; $('#mini-evidence').textContent = '0'; $('#risk-value').textContent = '—'; $('#risk-gauge').style.background = 'conic-gradient(var(--cyan) 0deg,var(--line) 0deg)'; $('#risk-caption').textContent = 'Awaiting evidence assessment.'; $('#pattern-chip').textContent = 'PATTERN —'; $('#recommendation-action').textContent = 'NO RECOMMENDATION'; $('#recommendation-reason').textContent = 'The investigation has not produced a recommendation.'; $('#approval-route').textContent = 'ROUTE —'; ruleRow($('#recommendation-rules'), []); $('#nba-action').textContent = 'NO ACTION RECORDED'; $('#nba-reason').textContent = 'No next-best-action rationale returned.'; $('#nba-phase').textContent = 'PHASE —'; $('#nba-impact').textContent = ''; $('#final-action').textContent = 'No final action'; $('#final-reason').textContent = 'No final recommendation has been returned.'; ruleRow($('#final-rules'), []); $('#stop-reason').textContent = '—';
  for (const id of ['#graph-canvas', '#graph-legend', '#hypotheses-list', '#timeline', '#evidence-list', '#unknowns-list', '#contradictions-list', '#nba-initial-card', '#nba-final-card']) $(id).replaceChildren();
  $('#graph-count').textContent = '0 NODES'; $('#hypothesis-count').textContent = '0'; $('#step-count').textContent = '0 STEPS'; $('#evidence-count').textContent = '0 ITEMS'; $('#unknown-count').textContent = '0'; $('#contradiction-count').textContent = '0';
}

function renderHypotheses(result) { const list = $('#hypotheses-list'); list.replaceChildren(); $('#hypothesis-count').textContent = result.hypotheses?.length ?? 0; if (!result.hypotheses?.length) { list.innerHTML = '<div class="empty-list">No hypotheses returned by the API.</div>'; return; } for (const h of result.hypotheses) list.append(itemCard(`${h.id} · ${text(h.status)}`, h.claim, `confidence ${percent(h.confidence)} · support ${h.supporting?.length ?? 0} · contra ${h.contradicting?.length ?? 0}`, h.status === 'supported' ? 'supports' : h.status === 'rejected' || h.status === 'contradicted' ? 'contradicts' : 'neutral')); }
function renderEvidence(result) { const list = $('#evidence-list'); list.replaceChildren(); $('#evidence-count').textContent = `${result.evidence_items?.length ?? 0} ITEMS`; if (!result.evidence_items?.length) { list.innerHTML = '<div class="empty-list">No evidence items returned.</div>'; return; } for (const e of result.evidence_items) list.append(itemCard(e.claim, `${text(e.kind)} · ${text(e.source)}`, `ref ${e.ref} · ${text(e.stance)}${e.entity_ids?.length ? ` · ${e.entity_ids.join(', ')}` : ''}`, e.stance === 'supports' ? 'supports' : e.stance === 'contradicts' ? 'contradicts' : 'neutral')); }
function renderUncertainty(result) { const unknowns = $('#unknowns-list'); const contradictions = $('#contradictions-list'); unknowns.replaceChildren(); contradictions.replaceChildren(); $('#unknown-count').textContent = result.unknowns?.length ?? 0; $('#contradiction-count').textContent = result.contradictions?.length ?? 0; if (!result.unknowns?.length) unknowns.innerHTML = '<div class="empty-list">No unknowns returned.</div>'; else for (const u of result.unknowns) unknowns.append(itemCard(u.id, u.question, `${text(u.status)} · ${u.why_it_matters ?? ''}`, u.status === 'open' ? 'contradicts' : 'neutral')); if (!result.contradictions?.length) contradictions.innerHTML = '<div class="empty-list">No contradictions returned.</div>'; else for (const c of result.contradictions) contradictions.append(itemCard(c.id, c.description, `${text(c.severity)} · ${text(c.resolution)}`, c.resolution === 'unresolved' ? 'contradicts' : 'neutral')); }
function renderTimeline(result) { const list = $('#timeline'); list.replaceChildren(); $('#step-count').textContent = `${result.steps?.length ?? 0} STEPS`; if (!result.steps?.length) { list.innerHTML = '<div class="empty-list">No investigation steps returned.</div>'; return; } for (const step of result.steps) { const row = document.createElement('div'); row.className = 'timeline-item'; row.innerHTML = `<div class="step-number">${step.step_number}</div><div class="step-kind">${text(step.type)}</div><div class="step-copy"><strong></strong><p></p></div>`; row.querySelector('strong').textContent = step.description; row.querySelector('p').textContent = step.details ?? ''; list.append(row); } }
function nbaCard(target, nba, label) { target.replaceChildren(); const small = document.createElement('small'); small.textContent = label; const strong = document.createElement('strong'); strong.textContent = actionName(nba?.selected_action); const p = document.createElement('p'); p.textContent = nba?.reason ?? 'No rationale returned.'; const meta = document.createElement('p'); meta.className = 'stack-meta'; meta.textContent = `${text(nba?.approval_route)} · ${nba?.evidence_used?.length ?? 0} evidence refs`; target.append(small, strong, p, meta); }


function renderGraph(active) {
  const canvas = $('#graph-canvas'); canvas.replaceChildren(); const evidence = active?.caseDetail?.evidence ?? []; const nodes = new Map(); const edges = [];
  const add = (id, type, label = id) => { if (id && !nodes.has(String(id))) nodes.set(String(id), { id: String(id), type, label: String(label) }); };
  const link = (from, to, label) => { if (from && to && from !== to) edges.push({ from: String(from), to: String(to), label }); };
  for (const item of evidence) { const d = item.data ?? {};
    if (d.txn) { const txnId = d.txn.txn_id ?? active?.transaction?.txn_id; add(txnId, 'transaction', 'Transaction'); add(d.txn.card_id, 'card', 'Card'); add(d.txn.customer_id, 'customer', 'Customer'); link(txnId, d.txn.card_id, 'MADE'); link(d.txn.card_id, d.txn.customer_id, 'OWNS'); add(d.txn.device_id, 'device', 'Device'); link(txnId, d.txn.device_id, 'FROM_DEVICE'); add(d.txn.region ?? d.txn.addr1, 'region', 'Region'); link(txnId, d.txn.region ?? d.txn.addr1, 'BILLED_IN'); }
    if (d.kind && d.value && Array.isArray(d.cards)) for (const card of d.cards) { add(card.card_id, 'card', 'Connected card'); add(d.value, d.kind === 'device' ? 'device' : d.kind === 'region' ? 'region' : 'entity', d.value); link(card.card_id, d.value, `shared ${d.kind}`); }
    if (Array.isArray(d.neighbour_cards)) for (const card of d.neighbour_cards) { add(card.card_id, 'card', 'Neighbour card'); if (card.via) { const [kind, value] = card.via.split(':'); add(value ?? card.via, kind ?? 'linked', value ?? card.via); link(card.card_id, value ?? card.via, `via ${kind ?? 'link'}`); } }
  }
  if (!nodes.size) { const empty = document.createElement('div'); empty.className = 'empty-list'; empty.textContent = 'No structured relationship payload was returned for the persisted evidence.'; canvas.append(empty); $('#graph-count').textContent = '0 NODES'; $('#graph-legend').replaceChildren(); return; }
  const list = [...nodes.values()].slice(0, 24), width = Math.max(520, list.length * 70), height = 260, centerX = width / 2, centerY = height / 2, radiusX = Math.max(90, width / 2 - 65), radiusY = 92;
  const positions = new Map(list.map((node, index) => { const angle = -Math.PI / 2 + index * Math.PI * 2 / list.length; return [node.id, { x: centerX + Math.cos(angle) * radiusX, y: centerY + Math.sin(angle) * radiusY }]; }));
  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); svg.setAttribute('viewBox', `0 0 ${width} ${height}`); svg.setAttribute('role', 'img'); svg.setAttribute('aria-label', 'Relationships returned by graph evidence');
  for (const edge of edges) { const a = positions.get(edge.from), b = positions.get(edge.to); if (!a || !b) continue; const line = document.createElementNS('http://www.w3.org/2000/svg', 'line'); line.setAttribute('x1', a.x); line.setAttribute('y1', a.y); line.setAttribute('x2', b.x); line.setAttribute('y2', b.y); line.setAttribute('class', 'graph-edge'); const title = document.createElementNS('http://www.w3.org/2000/svg', 'title'); title.textContent = `${edge.from} —${edge.label}→ ${edge.to}`; line.append(title); svg.append(line); }
  for (const node of list) { const p = positions.get(node.id), group = document.createElementNS('http://www.w3.org/2000/svg', 'g'); group.setAttribute('class', `graph-node ${node.type}${node.id === String(active?.transaction?.txn_id) ? ' target' : ''}`); group.setAttribute('transform', `translate(${p.x},${p.y})`); const circle = document.createElementNS('http://www.w3.org/2000/svg', 'circle'); circle.setAttribute('r', node.type === 'transaction' ? 13 : 9); group.append(circle); const label = document.createElementNS('http://www.w3.org/2000/svg', 'text'); label.setAttribute('x', 0); label.setAttribute('y', 23); label.setAttribute('text-anchor', 'middle'); label.textContent = node.label.length > 19 ? `${node.label.slice(0, 18)}…` : node.label; group.append(label); svg.append(group); }
  canvas.append(svg); $('#graph-count').textContent = `${nodes.size} NODES · ${edges.length} EDGES`; $('#graph-legend').innerHTML = '<span><i class="legend-dot target"></i>Transaction</span><span><i class="legend-dot"></i>Card / entity</span><span><i class="legend-dot device"></i>Device</span><span><i class="legend-dot region"></i>Region</span>';
}


function renderResult(active) {
  const result = active.result; const probability = result.fraud_probability; const degrees = probability == null ? 0 : Math.max(0, Math.min(1, Number(probability))) * 360; setView('results');
  $('#case-title').textContent = `Transaction ${active.transactionId} · Case ${result.case_id}`; $('#case-id-chip').textContent = result.case_id; $('#case-status-chip').textContent = text(result.status).toUpperCase(); $('#mini-case-id').textContent = result.case_id; $('#case-mini').hidden = false; $('#mini-step').textContent = result.steps_count ?? 0; $('#mini-evidence').textContent = result.evidence_count ?? 0;
  $('#risk-value').textContent = percent(probability); $('#risk-gauge').style.background = `conic-gradient(${probability != null && probability >= .7 ? 'var(--red)' : probability != null && probability >= .4 ? 'var(--amber)' : 'var(--green)'} ${degrees}deg,var(--line) 0deg)`; $('#pattern-chip').textContent = `PATTERN ${text(result.assessed_pattern, 'NONE')}`; $('#risk-caption').textContent = result.assessed_pattern ? `Pattern returned: ${result.assessed_pattern}` : 'No documented pattern was returned.';
  const rec = result.recommendation; $('#recommendation-action').textContent = actionName(rec?.action); $('#recommendation-reason').textContent = rec?.reason ?? 'No recommendation reason returned.'; $('#approval-route').textContent = `ROUTE ${text(rec?.route)}`; ruleRow($('#recommendation-rules'), rec?.citing_rules);
  const nba = result.nba_final ?? result.nba_initial; $('#nba-action').textContent = actionName(nba?.selected_action); $('#nba-reason').textContent = nba?.reason ?? 'No next-best-action reason returned.'; $('#nba-phase').textContent = `PHASE ${text(nba?.phase)}`; $('#nba-impact').textContent = nba?.expected_impact ?? '';
  $('#final-action').textContent = actionName(rec?.action); $('#final-reason').textContent = rec?.reason ?? 'No final recommendation returned.'; ruleRow($('#final-rules'), rec?.citing_rules); $('#stop-reason').textContent = result.stop_reason ?? 'No stop reason returned.';
  renderHypotheses(result); renderEvidence(result); renderUncertainty(result); renderTimeline(result); nbaCard($('#nba-initial-card'), result.nba_initial, 'INITIAL NBA'); nbaCard($('#nba-final-card'), result.nba_final, 'FINAL NBA'); renderGraph(active);
}
async function loadHealth() {
  try { const [health, config] = await Promise.all([api('/health'), api('/config')]); const kind = health.backend ?? health.kind ?? config.kind; const degraded = health.degraded ?? config.degraded; $('#backend-status').textContent = text(kind); $('#mode-status').textContent = degraded ? 'DEGRADED' : 'LIVE'; const banner = $('#mode-banner'); banner.hidden = !degraded; banner.textContent = degraded ? 'LOCAL SIMULATION — graph evidence is from the derived local projection, not TigerGraph.' : 'Configured graph backend is active.'; setApiStatus(true, 'Connected'); } catch (error) { $('#backend-status').textContent = 'Unavailable'; $('#mode-status').textContent = 'OFFLINE'; setApiStatus(false, 'Unavailable'); showError(error); }
}


async function investigate() {
  const transactionId = $('#transaction-id').value.trim();
  if (!transactionId) { setInputStatus('Enter a transaction ID before starting an investigation.', 'error'); return; }
  const requestId = ++state.requestId; clearRenderedCase(); state.pendingTransactionId = transactionId; $('#investigate-button').disabled = true; setView('loading-state'); setInputStatus(`Pending investigation — transaction ${transactionId}.`, 'pending'); $('#loading-title').textContent = 'Resolving transaction…'; $('#loading-detail').textContent = 'Requesting transaction details from the graph backend.';
  try {
    const detail = await api('/tools/txn_detail', { method: 'POST', body: JSON.stringify({ txn_id: transactionId }) }); if (requestId !== state.requestId) return; const txn = detail.result?.data?.txn; if (!txn) throw new Error('Transaction detail returned no transaction payload.'); const resolvedTransactionId = String(txn.txn_id); if (resolvedTransactionId !== transactionId) throw new Error(`Transaction response mismatch: requested ${transactionId}, received ${resolvedTransactionId}.`);
    const body = { transaction_id: resolvedTransactionId, card_id: txn.card_id, customer_id: txn.customer_id, amount_usd: txn.amount_usd, risk_score: txn.risk_score, trigger_type: 'risk_score', description: `UI investigation for transaction ${resolvedTransactionId}` }; $('#loading-title').textContent = 'Running adaptive investigation…'; $('#loading-detail').textContent = 'Gathering graph evidence and updating hypotheses, uncertainty and next actions.';
    const response = await api('/api/v1/investigate', { method: 'POST', body: JSON.stringify(body) }); if (requestId !== state.requestId) return; const result = response.result; if (!result) throw new Error('Investigation response did not contain a result.'); $('#loading-title').textContent = 'Loading persisted evidence…'; $('#loading-detail').textContent = 'Reading the case record and raw graph evidence for the workspace.';
    const caseDetail = await api(`/api/v1/investigate/${encodeURIComponent(result.case_id)}`); if (requestId !== state.requestId) return; const record = recordFromCaseDetail(caseDetail); const recordTransactionId = transactionFromRecord(record); const recordCaseId = caseIdFromRecord(record); if (!record || !recordTransactionId || !recordCaseId) throw new Error('Persisted case did not include its case ID and transaction trigger.'); if (recordCaseId !== result.case_id) throw new Error(`Case response mismatch: requested ${result.case_id}, received ${recordCaseId}.`); if (recordTransactionId !== resolvedTransactionId) throw new Error(`Case transaction mismatch: submitted ${resolvedTransactionId}, persisted ${recordTransactionId}.`);
    const active = { caseId: result.case_id, transactionId: recordTransactionId, transaction: txn, result, caseDetail, record }; state.active = active; state.pendingTransactionId = null; $('#transaction-id').value = recordTransactionId; setInputStatus(`Active case: transaction ${recordTransactionId} · ${result.case_id}`, 'active'); renderResult(active);
  } catch (error) { if (requestId !== state.requestId) return; state.active = null; state.pendingTransactionId = null; showError(error); } finally { if (requestId === state.requestId) $('#investigate-button').disabled = false; }
}
$('#transaction-id').addEventListener('input', (event) => { const value = event.target.value.trim(); if (state.active && value && value !== state.active.transactionId) setInputStatus(`Pending investigation — transaction ${value} has not been submitted.`, 'pending'); else if (state.active && value === state.active.transactionId) setInputStatus(`Active case: transaction ${value} · ${state.active.caseId}`, 'active'); else if (!state.active && value) setInputStatus('Ready to investigate this transaction.', 'pending'); });
$('#investigate-form').addEventListener('submit', (event) => { event.preventDefault(); void investigate(); });
$('#retry-button').addEventListener('click', () => void investigate());
void loadHealth();

