/** @module policy/sar — Suspicious Activity Report decision + deterministic draft.
 *
 * Uses sarFilingHolds() from the policy module (README §3a): filing requires
 * confirmed/strongly-suspected fraud AND at least one hold. The draft narrative is a
 * deterministic template standing on its own (who/what/when/where/why/how). Nothing here
 * ever claims an external filing happened: statuses are NOT_REQUIRED /
 * SAR_RECOMMENDED / SAR_DRAFT_GENERATED only.
 */
import { sarFilingHolds, type ApprovalRoute } from './policy.js';

export type SarStatus = 'NOT_REQUIRED' | 'SAR_RECOMMENDED' | 'SAR_DRAFT_GENERATED';

export interface SarDecision {
  required: boolean;
  status: SarStatus;
  rationale: string;
  citing_rules: string[];
  evidence_refs: string[];
  exposure_usd: number;
  pattern: string | null;
  narrative: string;
  narrative_source: 'template' | 'llm';
  approval_route: ApprovalRoute;
  generated_at: string;
}

export interface SarInput {
  case_id: string;
  fraud_probability: number;
  fraud_confirmed_or_strong: boolean;
  exposure_usd: number;
  shared_element_link: boolean;
  coordinated_or_undocumented: boolean;
  pattern: string | null;
  citing_rules: string[];
  evidence_refs: string[];
  trigger: { transaction_id: string; card_id: string; customer_id: string; ts: string; description: string; channel?: string; region?: string };
  connected_card_count?: number;
}

export function buildSarDecision(input: SarInput): SarDecision {
  const holds = sarFilingHolds({
    fraudConfirmedOrStrong: input.fraud_confirmed_or_strong,
    exposureUsd: input.exposure_usd,
    sharedElementLink: input.shared_element_link,
    coordinatedOrUndocumented: input.coordinated_or_undocumented,
  });

  const base = {
    citing_rules: input.citing_rules.slice(),
    evidence_refs: input.evidence_refs.slice(0, 8),
    exposure_usd: input.exposure_usd,
    pattern: input.pattern,
    approval_route: ('L2' as ApprovalRoute), // FILE_REPORT routes to L2 per README approval table
    generated_at: new Date().toISOString(),
  };

  if (!holds.file) {
    const why = input.fraud_confirmed_or_strong
      ? 'Fraud is strongly suspected but no filing hold applies (exposure ≤ $1,000, no shared element, no coordinated/undocumented pattern).'
      : 'Fraud probability is below the confirmed/strongly-suspected bar for filing.';
    return {
      ...base,
      required: false,
      status: 'NOT_REQUIRED',
      rationale: why,
      narrative: `SAR not required for ${input.case_id}. ${why}`,
      narrative_source: 'template',
    };
  }

  const narrative = [
    `SUSPICIOUS ACTIVITY REPORT — DRAFT (status: SAR_DRAFT_GENERATED, not filed externally).`,
    `Case: ${input.case_id}. Alert opened ${input.trigger.ts}.`,
    `WHO: customer ${input.trigger.customer_id}, card ${input.trigger.card_id}${input.connected_card_count ? `, with ${input.connected_card_count} connected card(s) via shared elements` : ''}.`,
    `WHAT: flagged transaction ${input.trigger.transaction_id}; trigger — ${input.trigger.description}`,
    `WHEN: ${input.trigger.ts}.`,
    `WHERE: ${input.trigger.region ? `billing region ${input.trigger.region}` : 'billing region not yet established'}${input.trigger.channel ? `, channel ${input.trigger.channel}` : ''}.`,
    `WHY SUSPICIOUS: assessed pattern "${input.pattern ?? 'unresolved'}" at fraud probability ${input.fraud_probability.toFixed(2)}. Filing holds: ${holds.holds.join('; ')}.`,
    `POLICY: ${input.citing_rules.join(', ') || 'n/a'} (fraud policy R1–R10, README § Fraud Policy).`,
    `SUPPORTING EVIDENCE: ${input.evidence_refs.slice(0, 6).join(' | ') || 'see case record'}.`,
    `EXPOSURE: $${input.exposure_usd.toFixed(2)}.`,
    `HOW (action taken by the agent): draft prepared for L2 approval; recommended action recorded in the case. This draft is generated by the agent and has NOT been filed with any regulator.`,
  ].join('\n');

  return {
    ...base,
    required: true,
    status: 'SAR_DRAFT_GENERATED',
    rationale: `Confirmed/strongly-suspected fraud with hold(s): ${holds.holds.join('; ')}.`,
    narrative,
    narrative_source: 'template',
  };
}
