/** Real TigerGraph GraphBackend. Analytical tools call named installed GSQL queries. */
import { toolError, toolResult, type GraphBackend } from '../contract.js';
import { edges, executeInstalledQuery, health, publicTigerGraphConfig, queryFailure, vertices, type TigerGraphConfig } from './client.js';

export type TigerGraphBackend = GraphBackend & { probe(timeoutMs?: number): Promise<{ ok: boolean; ms: number; error?: string }> };
const Q: Record<string, string> = {
  txn_detail: 'hhgoa_txn_detail', card_window: 'hhgoa_card_window', card_history: 'hhgoa_card_history',
  device_neighbors: 'hhgoa_device_neighbors', region_cluster: 'hhgoa_region_cluster', email_neighbors: 'hhgoa_email_neighbors',
  linked_cards: 'hhgoa_linked_cards', card_component: 'hhgoa_card_component', card_centrality: 'hhgoa_card_centrality',
  shortest_card_path: 'hhgoa_shortest_card_path', card_testing_scan: 'hhgoa_card_testing_scan',
  similar_closed_cases: 'hhgoa_similar_closed_cases', graph_context: 'hhgoa_graph_context',
};
export function createTigerGraphBackend(config: TigerGraphConfig): TigerGraphBackend {
  const started = Date.now();
  const b = { kind: 'tigergraph', degraded: false, notes: ['Named installed GSQL queries via RESTPP; local projection is never substituted.'] } as TigerGraphBackend;
  b.probe = async (timeout = config.requestTimeoutMs) => { const t = Date.now(); try { const h = await health({ ...config, requestTimeoutMs: Math.max(100, Math.min(timeout, config.requestTimeoutMs)) }); return String(h.status ?? '').toLowerCase() === 'failed' ? { ok: false, ms: Date.now() - t, error: 'health failed' } : { ok: true, ms: Date.now() - t }; } catch (e) { return { ok: false, ms: Date.now() - t, error: queryFailure(e).message }; } };
  b.health = async () => { try { const [h, v, e] = await Promise.all([health(config), vertices(config, 'Transaction', 1), edges(config, 'MADE', 1)]); return toolResult(b, 'health', {}, { ...h, configured: publicTigerGraphConfig(config), sample: { transaction_vertices: v.length, made_edges: e.length } }); } catch (e) { const f = queryFailure(e); return toolError(b, 'health', {}, f.message, f.code); } };
  const run = async (tool: string, args: Record<string, unknown>) => { try { const results = await executeInstalledQuery(config, Q[tool], args); return toolResult(b, tool, args, { query_name: Q[tool], found: results.length > 0, results }); } catch (e) { const f = queryFailure(e); return toolError(b, tool, args, f.message, f.code); } };
  b.txnDetail = a => run('txn_detail', a); b.cardWindow = a => run('card_window', a); b.cardHistory = a => run('card_history', a); b.deviceNeighbors = a => run('device_neighbors', a); b.regionCluster = a => run('region_cluster', a); b.emailNeighbors = a => run('email_neighbors', a); b.linkedCards = a => run('linked_cards', a); b.cardComponent = a => run('card_component', a); b.cardCentrality = a => run('card_centrality', a); b.shortestCardPath = a => run('shortest_card_path', a); b.cardTestingScan = a => run('card_testing_scan', a); b.similarClosedCases = (f, k) => run('similar_closed_cases', { features: f, k: k ?? 5 }); b.graphContext = a => run('graph_context', a);
  const write = async (kind: 'case' | 'evidence' | 'audit', record: Record<string, unknown>) => { const tool = kind === 'case' ? 'write_case' : kind === 'evidence' ? 'write_evidence' : 'write_audit'; try { const r = await executeInstalledQuery(config, `hhgoa_upsert_${kind}`, { record }); return toolResult(b, tool, { case_id: record.case_id }, { written_to_graph: r.length > 0, written_count: r.length }); } catch (e) { const f = queryFailure(e); return toolError(b, tool, { case_id: record.case_id }, f.message, f.code); } };
  const writeMany = async (kind: 'evidence' | 'audit', caseId: string, items: Record<string, unknown>[]) => { const tool = kind === 'evidence' ? 'write_evidence' : 'write_audit'; let n = 0; try { for (const item of items) n += (await executeInstalledQuery(config, `hhgoa_upsert_${kind}`, { record: { case_id: caseId, ...item } })).length; return toolResult(b, tool, { case_id: caseId, count: items.length }, { written_to_graph: n > 0, written_count: n }); } catch (e) { const f = queryFailure(e); return toolError(b, tool, { case_id: caseId }, f.message, f.code); } };
  b.writeCase = r => write('case', r); b.updateCase = (id, p) => write('case', { case_id: id, ...p }); b.readCase = async ({ case_id }) => { try { const r = await executeInstalledQuery(config, 'hhgoa_read_case', { case_id }); return toolResult(b, 'read_case', { case_id }, { found: r.length > 0, record: r[0] ?? null }); } catch (e) { const f = queryFailure(e); return toolError(b, 'read_case', { case_id }, f.message, f.code); } }; b.writeEvidence = ({ case_id, items }) => writeMany('evidence', case_id, items); b.writeAudit = ({ events }) => writeMany('audit', '', events); b.loadMs = Date.now() - started; return b;
}